### ISSUE TITLE
Organize DistanceAcutest directory

### ISSUE THREAD

**Issue by AntonisZks** [AntonisZks/Information-Systems-Software-Development-Project#18]
**Organize** the contents of the `DistnaceAcutest` directory. Specifically **move** some files to the appropriate **location**, **delete** useless **files** and **add documentation** to the code.

Specifically the changes I suggest are:
- [x] Delete `DataVectorNew.h` since it is already implemented in the `/include/DataVector` directory.
- [x] Add prototypes for the `euclideanDistance()` and `manhattanDistance()` functions to the `/include/distance.h` file.
- [x] Move `euclideanDistance()` and `manhattanDistance()` code to the `/src/distance_functions.cpp` file.
- [x] Delete `readMain.cpp` and `readVectors.cpp` from the `/DistanceAcutest` directory.
- [x] Move `test_distance.cpp` to the `/tests` directory and rename it to `test_distance.cc`.
- [x] Add **documentation** to the `DataVector` class.
- [x] Add **documentation** to the `euclideanDistance()` and `manhattanDistance` functions.
- [x] Add **documentation** to the **test functions** of the `euclideanDistance()`.

Me @AntonisZks can take care of the documentation of the code, @StavrosJKw you can approve my suggestions above and do the rest.

**Comment by StavrosJKw** [comment]
Moved files to their corresponding directories (src/include/tests), cleared up some comments that where initially for testing/understanding, and updated them with the correct comment/descriptions
