### ISSUE TITLE
Optimization to the /src/graph_functions.cpp

### ISSUE THREAD

**Issue by AntonisZks** [AntonisZks/Information-Systems-Software-Development-Project#22]
I believe that `/src/graph_functions.cpp` needs some optimization. Specifically we can clean up the file a bit from comments and some useless code. The **`GreedySearch`** algorothm needs a little imprevement by adding comments on the code, and make it compatible with the `Graph` data structure we already have. Also the function needs to have a **better syntax** since many **STL structures** are being used, in order to make it work correclty. So I suggest:

- [x] Clean up the file from comments.
- [x] Delete the `Nodedata` struct.
- [x] Make the `GreedySearch` compatible with the structures we already have.
- [x] Add documentation to the `GreedySearch` function.

@EvitaChasioti can you take care of that?

**Comment by StavrosJKw** [comment]
Deleted unimportant comments and used namespace std to make code more readable in GreedySearch()

**Comment by AntonisZks** [comment]
I organized my version of the Greedy Search and did the above. You can see the changes in my branch.
