### ISSUE TITLE
Create Pruning Algorithm

### ISSUE THREAD

**Issue by AntonisZks** [AntonisZks/Information-Systems-Software-Development-Project#24]
We must start creating the `Pruning` function in the `/src/graph_functions.cpp` file, in order to use it in the **Vamana** algorithm later.

- [x] Create **pruning** **function protype** in the `/include/graphFunctions.h` file.
- [x] Implement the **pruning** function code.
- [x] Test the **pruning algorithm**.

@EvitaChasioti and @AntonisZks can work together on this.

**Comment by EvitaChasioti** [comment]
Pruning is ready for testing!
