### ISSUE TITLE
Add documentation

### ISSUE THREAD

**Issue by AntonisZks** [AntonisZks/Information-Systems-Software-Development-Project#26]
Add documentation to the code and create a `README.md` file for the whole project. For the documentation I suggest we use **java DocStrings**. A usage example is the following:
```cpp
/**
 * @brief Adds two numbers
 * 
 * @param num1 the first number
 * @param num2 the second number
 * 
 * @return the sum of num1 and num2
 */
int add numbers(int num1, int num2) {
  return num1 + num2;
}
```

- [x] Add **documentation** to the **code**.
- [x] Create `README.md` for the project.

**Comment by StavrosJKw** [comment]
I have started documenting our project
