### ISSUE TITLE
Re-Implementation of GreedySearch

### ISSUE THREAD

**Issue by AntonisZks** [AntonisZks/Information-Systems-Software-Development-Project#41]
I suggest we try to re-implement the `GreedySearch` algorithm in order to be compatible with the Graph data structure.

- [x] Re-implement **Greedy Search**
- [x] Test the algorithm

**Comment by EvitaChasioti** [comment]
I made GreedySearch more compatible and write some comments.

**Comment by AntonisZks** [comment]
I made a version of Greedy Search too
