### ISSUE TITLE
Add further features

### ISSUE THREAD

**Issue by AntonisZks** [AntonisZks/Information-Systems-Software-Development-Project#43]
I thinks that we need to consider making some **extra features** for the application according to the **paper**. Specifically:

1. Add an evaluation function that calculates the **recall** of a search process, and describes how good the search algorithm is.
2. In order to do the above we need to **include** in our application the **ground-truth** dataset file and start experimenting with this.
3. By now we have done the `GreedySearch`, but there is a little problem with the start node. At this point we are setting the start node to be the first node of the graph. In fact it would be more suitable to set the start node of the search to be the **mediod** node which is the node located at the center of the graph geometrically.

- [x] **Add recall** evaluation to the search process.
- [x] **Include ground-truth** to the application.
- [x] **Calculate mediod** node and start the search process from this.

The **recall** evaluation can be calculated using the following formula: $Recall=\frac{|X \cap G|}{k}$ where **$X$** is the set containing the **approximate neighbors** and **$G$** is the set containing the **exact neighbors**.

**Comment by StavrosJKw** [comment]
I have started working on this @AntonisZks
