### ISSUE TITLE
Extend the DataVector class

### ISSUE THREAD

**Issue by AntonisZks** [AntonisZks/Information-Systems-Software-Development-Project#60]
Since we are dealing with a **different** type of data, I suggest we extend our existed `DataVector` class to be compatible with the current state of the project. Specifically, what I suggest is creatiing **two** new classes, **`BaseDataVector`** and **`QueryDataVector`** that both are **sub-classes** of the main `DataVector` class.

According to the [dataset website](https://transactional.blog/sigmod-contest/2024)

1. The `BaseDataVector` class will have **two** extra attributes: 
    - **C** (Categorical Attribute) and 
    - **T** (Timestump Attribute).
3. The `QueryDataVector` class will have **four** extra attributes: 
    - **query type** that can take values 0, 1, 2 and 3, 
    - **v** (for the categorical value C), 
    - **l** (for the timestamp value T), and 
    - **r** (for the timestamp value T).

The resulted classes should look somthing like the following:
```cpp
/* Base Data Vector Class */
template <typename dvector_t>
class BaseDataVector : public DataVector {
private:
    unsigned int C, T; // Extra Attributes
    ...
public:
    ...
};
```
and
```cpp
/* Query Data Vector Class */
template <typename dvector_t>
class QueryDataVector : public DataVector {
private:
    unsigned int v, l, r; // Extra attributes
    ...
public:
    ...
};
```

@StavrosJKw can you work on this? Any other suggestion about this topic is accepted.

**Comment by StavrosJKw** [comment]
Thank you for Issuing this @AntonisZks , I will get right on it

**Comment by StavrosJKw** [comment]
I implemented the subclasses of DataVector, that will help us read the new datasets. They can be found in the file `BQDataVectors.h` in the directory 
```
include/DataStructures/DataVector/BQDataVector.h
```

I am still considering enhancing the classes with more methods. If the need arises further in development I will add them.
