### ISSUE TITLE
FilteredGreedySearch Implementation

### ISSUE THREAD

**Issue by AntonisZks** [AntonisZks/Information-Systems-Software-Development-Project#61]
We should start implementing the **filtered** version of the **Greedy Search** Algorithm. What I suggest is implementing this algorithm as a function `FilteredGreedySearch()` inside the `include/Algorithms/GreedySearch.h` file. For the implementation of this function I suggest following a **standard prototype** that is related to the [paper's](https://dl.acm.org/doi/pdf/10.1145/3543507.3583552) pseudocode. The prototype, I suggest is the following:
```cpp
template <typename graph_t>
std::pair<std::set<graph_t>, std::set<graph_t>> FilteredGreedySearch(
      const Graph<graph_t>& G,
      const std::vector<GraphNode<graph_t>>& S, 
      const graph_t& xq, 
      const unsigned int k, 
      const unsigned int L, 
      const std::vector<FilterType>& queryFilters
);
```
where `FilterType` is going to be a special type of data and specifically an **enumeration** that collects all the possible **filter actions** we can come across. Specifically the enumeration should look something like this:
```cpp
enum FilterType {
    C_EQUALS_v,    // For xq.v == s.C
    l_LEQ_T_LEQ_r, // for xq.l <= s.T and s.T <= xq.r
};
```
With the above definition of the **filter type** we can use values of this structure and store them inside a sequence. For example we can create something like the following:
```cpp
std::vector<FilterType> filters = { C_EQUALS_v, l_LEQ_T_LEQ_r };
```
In the code above we are describing that the filters we currently have are:
1. the **Categorical value checking** and
2. the **Timestamp value checking**

So, according to this vector, we can take specific actions about the corresponding vector.
> [!IMPORTANT] 
> The expression $F_s \cap F_x \neq \emptyset$ basically means that we are checking if the current query node **$x_q$** satisfy the current **filter action** with **$s$** at this point. For example if the filter action is `C_EQUALS_v` then we have to check if the expression
```cpp
xq.v == s.C
```
is true.

I can implement the `FilterType` enumeration. @EvitaChasioti can you implement the logic above for the `FilteredGreedySearch` algorithm?

**Comment by EvitaChasioti** [comment]
FilteredGreedySearch just committed
